export const data = [
  {
    id: 1,
    group: "land",
    icon: "tree",
    title: "Jahorina Base Camp Trek With Team Professionals",
    comment: "Unforgettable experience!",
    coverImg:
      "https://images.unsplash.com/photo-1551632811-561732d1e306?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80",
    images: ["../assets/images/hiking.jpg", "../assets/images/rest.jpg"],
    category: "Trekking and Hiking",
    subcategory: "Multi-day treks hikes",
    price: "120",
    level: "7",
    text: "We are opening the 9th season at the Olympic tracks on March 11, 2023! You all know how looks the new skyrunning format. Last year was the first Skyrunning championship in Spain. Also the Jahorina race, the only one in that format in this part of Europe.",
    date: "May 14th 2023",
    length: "4",
    age: "7-77",
  },
  {
    id: 2,
    group: "aerial",
    icon: "bird",
    title: "SkyRace & SkyUltra",
    comment: "Unforgettable experience!",
    coverImg:
      "https://images.unsplash.com/photo-1629141334092-9f57a94b6686?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80",
    images: [],
    category: "Trekking and Hiking",
    subcategory: "Multi-day treks hikes",
    price: "120",
    level: "7",
    text: "We are opening the 9th season at the Olympic tracks on March 11, 2023! You all know how looks the new skyrunning format. Last year was the first Skyrunning championship in Spain. Also the Jahorina race, the only one in that format in this part of Europe.",
    date: "May 14th 2023",
    length: "4",
    age: "7-77",
  },
  {
    id: 3,
    group: "water",
    icon: "fish",
    title: "Prokletije VK",
    comment: "Unforgettable experience!",
    coverImg:
      "https://images.unsplash.com/photo-1682687981630-cefe9cd73072?ixlib=rb-4.0.3&ixid=MnwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1742&q=80",
    images: [],
    category: "Trekking and Hiking",
    subcategory: "Multi-day treks hikes",
    price: "120",
    level: "7",
    text: "We are opening the 9th season at the Olympic tracks on March 11, 2023! You all know how looks the new skyrunning format. Last year was the first Skyrunning championship in Spain. Also the Jahorina race, the only one in that format in this part of Europe.",
    date: "May 14th 2023",
    length: "4",
    age: "7-77",
  },
  {
    id: 4,
    group: "aerial",
    icon: "bird",
    title: "Sky Diving",
    comment: "Unforgettable experience!",
    coverImg:
      "https://images.unsplash.com/photo-1565639828644-ff8e088ebfa8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1548&q=80",
    images: [],
    category: "Trekking and Hiking",
    subcategory: "Multi-day treks hikes",
    price: "120",
    level: "7",
    text: "We are opening the 9th season at the Olympic tracks on March 11, 2023! You all know how looks the new skyrunning format. Last year was the first Skyrunning championship in Spain. Also the Jahorina race, the only one in that format in this part of Europe.",
    date: "May 14th 2023",
    length: "4",
    age: "7-77",
  },
];
