export const data = [
  {
    id: 1,
    group: "land",
    icon: "tree",
    title: "Sky2Run Trail Running Camp",
    comment: "Unforgettable experience!",
    coverImg:
      "https://images.unsplash.com/photo-1498625503930-06e0955bb992?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80",
    images: [
      "https://images.unsplash.com/photo-1565639828644-ff8e088ebfa8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1548&q=80",
      "https://images.unsplash.com/photo-1565639828644-ff8e088ebfa8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1548&q=80",
    ],
    category: "Trekking and Hiking",
    subcategory: "Multi-day treks hikes",
    price: "980",
    level: "7",
    text: `Sky2Run is the first ever Trail running camp to be based in the wild and beautiful Durmitor mountain range in Montenegro. The name Durmitor derives from the Celtic “dru mi tore” which means “mountain filled with water”. It has 18 glacial lakes, nicknamed “Gorske oči” (“Eyes of the Mountain”). The biggest and the most attractive is Crno jezero (Black lake). We will visit some of these lakes during the week. It has 48 peaks above 2000m and we will climb some of the most beautiful of them. Upon arrival at Durmitor, you will pass over the magnificent Tara bridge, below which runs Europe’s deepest gorge. We will be based at high altitude, at 1500m, and each day we will run with chamois and eagles, climb some of the highest and most stunning mountains of the national park, and practise technical skills of trail running with Gregory Vollet, one of the world's best mountain running coaches. Accommodation is in 3-bed rooms in the Hotel Žabljak, situated in the centre of the highest town in the Balkans at an altitude of 1500m. The town itself is within the Durmitor national park, a UNESCO World Heritage Site, meaning that some of the finest and wildest mountains in Europe are just a few minutes away. You will train with one of the most recognised trail running coaches in the world, Greg Vollet.
We will practice uphill and downhill running techniques - with different approaches for ultra and shorter trail races. You will receive a sign-up package with gifts from our sponsors, as well as an official t-shirt of the Sky2Run Trail Running Camp (more details to follow). Get ready to become a stronger trail runner, have a wonderful time in these beautiful and wild Balkan mountains, and make new friends (especially chamois).`,
    date: "May 28th 2023",
    length: "7",
    additionalInfo: "Max number: 30",
    location: {
      latitude: 43.154942,
      longitude: 19.120951,
    },
  },
  {
    id: 2,
    group: "aerial",
    icon: "bird",
    title: "SkyRace & SkyUltra",
    comment: "Unforgettable experience!",
    coverImg:
      "https://images.unsplash.com/photo-1629141334092-9f57a94b6686?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80",
    images: [],
    category: "Trekking and Hiking",
    subcategory: "Multi-day treks hikes",
    price: "120",
    level: "7",
    text: "We are opening the 9th season at the Olympic tracks on March 11, 2023! You all know how looks the new skyrunning format. Last year was the first Skyrunning championship in Spain. Also the Jahorina race, the only one in that format in this part of Europe.",
    date: "May 14th 2023",
    length: "4",
    additionalInfo: "7-77",
    location: {
      latitude: 43.737259,
      longitude: 28.56749,
    },
  },
  {
    id: 3,
    group: "water",
    icon: "fish",
    title: "Prokletije VK",
    comment: "Unforgettable experience!",
    coverImg:
      "https://images.unsplash.com/photo-1682687981630-cefe9cd73072?ixlib=rb-4.0.3&ixid=MnwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1742&q=80",
    images: [],
    category: "Trekking and Hiking",
    subcategory: "Multi-day treks hikes",
    price: "120",
    level: "7",
    text: "We are opening the 9th season at the Olympic tracks on March 11, 2023! You all know how looks the new skyrunning format. Last year was the first Skyrunning championship in Spain. Also the Jahorina race, the only one in that format in this part of Europe.",
    date: "May 14th 2023",
    length: "4",
    additionalInfo: "7-77",
    location: {
      latitude: 42.439999,
      longitude: 19.812,
    },
  },
  {
    id: 4,
    group: "aerial",
    icon: "bird",
    title: "Sky Diving",
    comment: "Unforgettable experience!",
    coverImg:
      "https://images.unsplash.com/photo-1565639828644-ff8e088ebfa8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1548&q=80",
    images: [],
    category: "Trekking and Hiking",
    subcategory: "Multi-day treks hikes",
    price: "120",
    level: "7",
    text: "We are opening the 9th season at the Olympic tracks on March 11, 2023! You all know how looks the new skyrunning format. Last year was the first Skyrunning championship in Spain. Also the Jahorina race, the only one in that format in this part of Europe.",
    date: "May 14th 2023",
    length: "4",
    additionalInfo: "7-77",
    location: {
      latitude: 43.219978,
      longitude: 22.312321,
    },
  },
];
